# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/rotateWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rotateWindow(object):
    def setupUi(self, rotateWindow):
        rotateWindow.setObjectName("rotateWindow")
        rotateWindow.resize(430, 272)
        self.centralwidget = QtWidgets.QWidget(rotateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 411, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.filenameLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.filenameLineEdit.setObjectName("filenameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.filenameLineEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.rotationLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.rotationLineEdit.setObjectName("rotationLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rotationLineEdit)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget_2)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        rotateWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(rotateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        rotateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(rotateWindow)
        self.statusbar.setObjectName("statusbar")
        rotateWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(rotateWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(rotateWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(rotateWindow)
        self.buttonBox.rejected.connect(rotateWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(rotateWindow)

    def retranslateUi(self, rotateWindow):
        _translate = QtCore.QCoreApplication.translate
        rotateWindow.setWindowTitle(_translate("rotateWindow", "PDF Editor"))
        self.label_2.setText(_translate("rotateWindow", "Rotation"))
        self.label.setText(_translate("rotateWindow", "File"))
        self.menuFile.setTitle(_translate("rotateWindow", "File"))
        self.menuHelp.setTitle(_translate("rotateWindow", "Help"))
        self.actionOpen.setText(_translate("rotateWindow", "Open"))
        self.actionAbout.setText(_translate("rotateWindow", "About"))
